version: 2.1

jobs:
    build:
        parameters:
            java:
                type: string
        docker:
            # specify the version you desire here
            - image: circleci/clojure:<< parameters.java >>

        working_directory: ~/repo

        environment:
            JVM_OPTS: -Xmx3200m

        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "project.clj" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: |
                sudo apt install libgtk-3-0 libxtst6 --no-install-recommends -y
                # 'lein cloverage -h' will pull down further deps for the plugin without actually running it
                lein deps && lein cloverage -h > /dev/null

            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "project.clj" }}

            - run: ./run-tests.sh

workflows:
    version: 2.1
    workflow:
        jobs:
            - build:
                matrix:
                    parameters:
                        java: ["openjdk-11", "openjdk-15"]